# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(choices=[('HM', 'Human'), ('EL', 'Elf'), ('OW', 'Orc'), ('DW', 'Dwarf'), ('WW', 'WareWolf')], max_length=3)),
                ('image', models.ImageField(upload_to='Character/%Y-%m-%d/')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('game_type', models.CharField(choices=[('SP', 'Singleplay'), ('MP', 'Multiplay')], default='SP', max_length=3)),
                ('data_begin', models.DateField(auto_now=True, null=True)),
                ('data_end', models.DateField(blank=True)),
                ('image', models.ImageField(upload_to='Room/%Y-%m-%d/')),
            ],
        ),
    ]
