# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_delete_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(choices=[('HM', 'Human'), ('EL', 'Elf'), ('OW', 'Orc'), ('DW', 'Dwarf'), ('WW', 'WareWolf')], max_length=3)),
                ('image', models.ImageField(upload_to='Character')),
            ],
        ),
    ]
