# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-23 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20170523_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
